server.port=9090

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
spring.datasource.username=shareit_user
spring.datasource.password=shareit_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true